import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:omdb_api/src/models/omdb_rating.dart';

part 'omdb_item.freezed.dart';
part 'omdb_item.g.dart';

String? nullConverter(String? value) {
  if (value == null || value == 'N/A') return null;
  return value;
}

@Freezed(unionKey: 'Type')
class OMDBItem with _$OMDBItem {
  const factory OMDBItem.movie({
    @JsonKey(name: 'Title') required String title,
    @JsonKey(name: 'Year') required String year,
    @JsonKey(name: 'Rated', fromJson: nullConverter) String? rate,
    @JsonKey(name: 'Released', fromJson: nullConverter) String? releaseDate,
    @JsonKey(name: 'Runtime', fromJson: nullConverter) String? runtime,
    @JsonKey(name: 'Genre') required String genres,
    @JsonKey(name: 'Director', fromJson: nullConverter) String? directors,
    @JsonKey(name: 'Writer', fromJson: nullConverter) String? writers,
    @JsonKey(name: 'Actors', fromJson: nullConverter) String? actors,
    @JsonKey(name: 'Plot') required String plot,
    @JsonKey(name: 'Language') required String language,
    @JsonKey(name: 'Country') required String countries,
    @JsonKey(name: 'Awards', fromJson: nullConverter) String? awards,
    @JsonKey(name: 'Poster', fromJson: nullConverter) String? posterUrl,
    @JsonKey(name: 'Ratings') required List<OMDBRating> ratings,
    @JsonKey(name: 'Metascore', fromJson: nullConverter) String? metascore,
    @JsonKey(fromJson: nullConverter) String? imdbRating,
    @JsonKey(fromJson: nullConverter) String? imdbVotes,
    @JsonKey(name: 'imdbID') required String imdbId,
    @JsonKey(fromJson: nullConverter) String? tomatoMeter,
    @JsonKey(fromJson: nullConverter) String? tomatoImage,
    @JsonKey(fromJson: nullConverter) String? tomatoRating,
    @JsonKey(fromJson: nullConverter) String? tomatoReviews,
    @JsonKey(fromJson: nullConverter) String? tomatoFresh,
    @JsonKey(fromJson: nullConverter) String? tomatoRotten,
    @JsonKey(fromJson: nullConverter) String? tomatoConsensus,
    @JsonKey(fromJson: nullConverter) String? tomatoUserMeter,
    @JsonKey(fromJson: nullConverter) String? tomatoUserRating,
    @JsonKey(fromJson: nullConverter) String? tomatoUserReviews,
    @JsonKey(name: 'tomatoURL', fromJson: nullConverter) String? tomatoUrl,
    @JsonKey(name: 'DVD', fromJson: nullConverter) String? dvdReleaseDate,
    @JsonKey(name: 'BoxOffice', fromJson: nullConverter) String? boxOffice,
    @JsonKey(name: 'Production', fromJson: nullConverter) String? production,
    @JsonKey(name: 'Website', fromJson: nullConverter) String? website,
    @JsonKey(name: 'Response') required String response,
  }) = OMDBItemMovie;
  const factory OMDBItem.series({
    @JsonKey(name: 'Title') required String title,
    @JsonKey(name: 'Year') required String year,
    @JsonKey(name: 'Rated', fromJson: nullConverter) String? rate,
    @JsonKey(name: 'Released', fromJson: nullConverter) String? releaseDate,
    @JsonKey(name: 'Runtime', fromJson: nullConverter) String? runtime,
    @JsonKey(name: 'Genre', fromJson: nullConverter) String? genres,
    @JsonKey(name: 'Director', fromJson: nullConverter) String? directors,
    @JsonKey(name: 'Writer', fromJson: nullConverter) String? writers,
    @JsonKey(name: 'Actors', fromJson: nullConverter) String? actors,
    @JsonKey(name: 'Plot', fromJson: nullConverter) String? plot,
    @JsonKey(name: 'Language', fromJson: nullConverter) String? language,
    @JsonKey(name: 'Country', fromJson: nullConverter) String? countries,
    @JsonKey(name: 'Awards', fromJson: nullConverter) String? awards,
    @JsonKey(name: 'Poster', fromJson: nullConverter) String? posterUrl,
    @JsonKey(name: 'Ratings') required List<OMDBRating> ratings,
    @JsonKey(name: 'Metascore', fromJson: nullConverter) String? metascore,
    @JsonKey(fromJson: nullConverter) String? imdbRating,
    @JsonKey(fromJson: nullConverter) String? imdbVotes,
    @JsonKey(name: 'imdbID') required String imdbId,
    @JsonKey(fromJson: nullConverter) String? tomatoMeter,
    @JsonKey(fromJson: nullConverter) String? tomatoImage,
    @JsonKey(fromJson: nullConverter) String? tomatoRating,
    @JsonKey(fromJson: nullConverter) String? tomatoReviews,
    @JsonKey(fromJson: nullConverter) String? tomatoFresh,
    @JsonKey(fromJson: nullConverter) String? tomatoRotten,
    @JsonKey(fromJson: nullConverter) String? tomatoConsensus,
    @JsonKey(fromJson: nullConverter) String? tomatoUserMeter,
    @JsonKey(fromJson: nullConverter) String? tomatoUserRating,
    @JsonKey(fromJson: nullConverter) String? tomatoUserReviews,
    @JsonKey(name: 'tomatoURL', fromJson: nullConverter) String? tomatoUrl,
    @JsonKey(fromJson: nullConverter) String? totalSeasons,
    @JsonKey(name: 'Response') required String response,
  }) = OMDBItemSeries;
  const factory OMDBItem.episode({
    @JsonKey(name: 'Title') required String title,
    @JsonKey(name: 'Year') required String year,
    @JsonKey(name: 'Rated', fromJson: nullConverter) String? rate,
    @JsonKey(name: 'Released', fromJson: nullConverter) String? releaseDate,
    @JsonKey(name: 'Season', fromJson: nullConverter) String? season,
    @JsonKey(name: 'Episode', fromJson: nullConverter) String? episode,
    @JsonKey(name: 'Runtime', fromJson: nullConverter) String? runtime,
    @JsonKey(name: 'Genre') required String genres,
    @JsonKey(name: 'Director', fromJson: nullConverter) String? directors,
    @JsonKey(name: 'Writer', fromJson: nullConverter) String? writers,
    @JsonKey(name: 'Actors', fromJson: nullConverter) String? actors,
    @JsonKey(name: 'Plot', fromJson: nullConverter) String? plot,
    @JsonKey(name: 'Language', fromJson: nullConverter) String? language,
    @JsonKey(name: 'Country', fromJson: nullConverter) String? countries,
    @JsonKey(name: 'Awards', fromJson: nullConverter) String? awards,
    @JsonKey(name: 'Poster', fromJson: nullConverter) String? posterUrl,
    @JsonKey(name: 'Ratings') required List<OMDBRating> ratings,
    @JsonKey(name: 'Metascore', fromJson: nullConverter) String? metascore,
    @JsonKey(fromJson: nullConverter) String? imdbRating,
    @JsonKey(fromJson: nullConverter) String? imdbVotes,
    @JsonKey(name: 'imdbID') required String imdbId,
    @JsonKey(name: 'seriesID', fromJson: nullConverter) String? seriesId,
    @JsonKey(fromJson: nullConverter) String? tomatoMeter,
    @JsonKey(fromJson: nullConverter) String? tomatoImage,
    @JsonKey(fromJson: nullConverter) String? tomatoRating,
    @JsonKey(fromJson: nullConverter) String? tomatoReviews,
    @JsonKey(fromJson: nullConverter) String? tomatoFresh,
    @JsonKey(fromJson: nullConverter) String? tomatoRotten,
    @JsonKey(fromJson: nullConverter) String? tomatoConsensus,
    @JsonKey(fromJson: nullConverter) String? tomatoUserMeter,
    @JsonKey(fromJson: nullConverter) String? tomatoUserRating,
    @JsonKey(fromJson: nullConverter) String? tomatoUserReviews,
    @JsonKey(name: 'tomatoURL', fromJson: nullConverter) String? tomatoUrl,
    @JsonKey(name: 'Response') required String response,
  }) = OMDBItemEpisode;

  factory OMDBItem.fromJson(Map<String, dynamic> json) =>
      _$OMDBItemFromJson(json);
}
